# Example URL
# https://github.com/cloudflare/cloudflared/releases/download/2020.11.11/cloudflared-linux-armv6
#DEFAULT_CLOUDFLARED_VERSION="2021.2.1"
DEFAULT_CLOUDFLARED_VERSION="latest"
DEFAULT_CLOUDFLARED_DESTINATION="/usr/local/bin"
DEFAULT_CLOUDFLARED_ARCHITECTURE="linux-armv6"

DEFAULT_DNS_PRIMARY="1.1.1.2"
DEFAULT_DNS_LOCAL_PORT="54"
DEFAULT_DNS_SECONDARY="1.0.0.2"
